version: '3'



#
# Descrição dos serviços
services:


  #
  # Servidor Web
  web-server:
    container_name: dev-php-webserver
    image: aeondigital/apache-php-7.4:dev
    volumes:
      #
      # Diretórios de arquivos de configuração.
      # Variáveis de ambiente
      - ./container-config/apache-php-7.4/etc/.env:/etc/.env
      #
      # Aplicação
      - .:/var/www/html
    ports:
      - 8080:80
