version: '3'

#
# Descrição dos serviços
services:

  # 
  # Servidor Web
  web-server:
    container_name: dev-php-webserver
    image: aeondigital/apache-php-7.4:dev
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
